export const ALL_RESULT_REQUEST = "ALL_RESULT_REQUEST";
export const ALL_RESULT_SUCCESS = "ALL_RESULT_SUCCESS";
export const ALL_RESULT_FAIL = "ALL_RESULT_FAIL";

export const NEW_RESULT_REQUEST = "NEW_RESULT_REQUEST";
export const NEW_RESULT_SUCCESS = "NEW_RESULT_SUCCESS";
export const NEW_RESULT_FAIL = "NEW_RESULT_FAIL";
export const NEW_RESULT_RESET = "NEW_RESULT_RESET";

export const GET_RESULT_REQUEST = "GET_RESULT_REQUEST";
export const GET_RESULT_SUCCESS = "GET_RESULT_SUCCESS";
export const GET_RESULT_FAIL = "GET_RESULT_FAIL";

export const UPDATE_RESULT_REQUEST = "UPDATE_RESULT_REQUEST";
export const UPDATE_RESULT_SUCCESS = "UPDATE_RESULT_SUCCESS";
export const UPDATE_RESULT_FAIL = "UPDATE_RESULT_FAIL";
export const UPDATE_RESULT_RESET = "UPDATE_RESULT_RESET";

export const DELETE_RESULT_SUCCESS = "DELETE_RESULT_SUCCESS";
export const DELETE_RESULT_FAIL = "DELETE_RESULT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";