export const ALL_STUDENT_REQUEST = "ALL_STUDENT_REQUEST"
export const ALL_STUDENT_SUCCESS = "ALL_STUDENT_SUCCESS"
export const ALL_STUDENT_FAIL = "ALL_STUDENT_FAIL"

export const NEW_STUDENT_REQUEST = "NEW_STUDENT_REQUEST";
export const NEW_STUDENT_SUCCESS = "NEW_STUDENT_SUCCESS";
export const NEW_STUDENT_FAIL = "NEW_STUDENT_FAIL";
export const NEW_STUDENT_RESET = "NEW_STUDENT_RESET";

export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAIL = "GET_STUDENT_FAIL";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";
export const UPDATE_STUDENT_RESET = "UPDATE_STUDENT_RESET";

export const DELETE_STUDENT = "DELETE_STUDENT";

export const CLEAR_ERRORS = "CLEAR_ERRORS" 